# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:8.12
    working_directory: ~/terng.life
    steps:
      - checkout
      - run: yarn
      - run: gatsby build
      - run: cd ~/terng.life && ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
