name: Build and run

on:
  push:
    branches:
      - "*"
      - "!staging"
      - "!master"

jobs:
  buildAndTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: whoami
      run: whoami
